# Creating array from scratch

In [21]:
import numpy as np

zeros = np.zeros((3,3))
print("[Zeros Array] : \n", zeros)

[Zeros Array] : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
ones = np.ones((3,3))
print("[Ones Array] : \n", ones)

[Ones Array] : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
full = np.full((3,3),True)
print("[FULL Array] : \n", full)

[FULL Array] : 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [24]:
random = np.random.random((3,3))
print("[Random Array] : \n", random)

[Random Array] : 
 [[0.6592695  0.15048245 0.12122896]
 [0.31145178 0.84050766 0.58457092]
 [0.23630467 0.22885231 0.65341568]]


In [25]:
sequence = np.arange(0, 11, 2)
print("[Sequence Array] : ", sequence) # no inclusive

[Sequence Array] :  [ 0  2  4  6  8 10]
