# Vector, Matrics and Tensor

In [8]:
from traceback import print_tb

import numpy as np

vector = np.array([1, 2, 3])
print("[VECTOR] : ", vector)

[VECTOR] :  [1 2 3]


In [9]:
matrics = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("[MATRICS] : \n", matrics)

[MATRICS] : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
tensor = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])

print("[TENSOR] : ", tensor)

[TENSOR] :  [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
