# Array Properties

In [8]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, True]
])

print("Shape : ", arr.shape)
print("Size : ", arr.size)
print("Dimension : ", arr.ndim)
print("Data Type : ", arr.dtype)

arr2 = np.full((2, 3), True)
print("Datatype : ", arr2.dtype)

Shape :  (2, 3)
Size :  6
Dimension :  2
Data Type :  int64
Datatype :  bool


## Array reshaping

In [9]:
arr3 = np.arange(20)
print("Original Array : ", arr3)

reshaped = arr3.reshape(4, 5)
print("Reshaped Array : ", reshaped)

flattened = reshaped.flatten()
print("Flattened : ", flattened)

# Ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled : ", raveled)


# Transpose
transpose = reshaped.T
print("Transpose : ", transpose)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array :  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Flattened :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Raveled :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Transpose :  [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
