# Numpy array operations

In [1]:
import numpy as np

arr_1 = np.arange(20)
print("Basic Slicing : ", arr_1[2:15])
print("With Step : ", arr_1[2:15:2])
print("Negative indexing : ", arr_1[-3])

Basic Slicing :  [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
With Step :  [ 2  4  6  8 10 12 14]
Negative indexing :  17


In [2]:
arr_2_2d = np.array([
    [1,3,5,4],
    [3,54,2,3],
    [4,5,6,8]
])

print("2D Array : \n", arr_2_2d)

print("Specefic element : ", arr_2_2d[1, 3])

2D Array : 
 [[ 1  3  5  4]
 [ 3 54  2  3]
 [ 4  5  6  8]]
Specefic element :  3


In [3]:
print("Entire row : ", arr_2_2d[1])
print("Entire column : ", arr_2_2d[:, 3])

Entire row :  [ 3 54  2  3]
Entire column :  [4 3 8]


### Sorting

In [4]:
unsorted_1 = np.array([4,8,1,798,2,5,71,5,9,87,1,2,8,7])
print("Unsorted : ", unsorted_1)
print("Sorted : ", np.sort(unsorted_1))

Unsorted :  [  4   8   1 798   2   5  71   5   9  87   1   2   8   7]
Sorted :  [  1   1   2   2   4   5   5   7   8   8   9  71  87 798]


In [5]:
unsorted_2_2d = np.array([
    [11,2],
    [31,4],
    [5,61],
])
print("Unsorted : \n", unsorted_2_2d)
print("\nSorted 2d array by Column: \n", np.sort(unsorted_2_2d, axis=0))
print("\nSorted 2d array by Row: \n", np.sort(unsorted_2_2d, axis=1))

Unsorted : 
 [[11  2]
 [31  4]
 [ 5 61]]

Sorted 2d array by Column: 
 [[ 5  2]
 [11  4]
 [31 61]]

Sorted 2d array by Row: 
 [[ 2 11]
 [ 4 31]
 [ 5 61]]


### Filter

In [6]:
numbers = np.arange(13)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers : ", even_numbers)

Even Numbers :  [ 0  2  4  6  8 10 12]


### Filter with mask

In [7]:
mask = numbers > 5
print("Mask : ", mask)
print("Number greater than 5 : ", numbers[mask])

Mask :  [False False False False False False  True  True  True  True  True  True
  True]
Number greater than 5 :  [ 6  7  8  9 10 11 12]


### Indexing vs np.where()

In [10]:
indices = [0, 2, 4]
print("Indices : ", numbers[indices])

where_result = np.where(numbers > 5)
print("Where result : ", numbers[where_result])

where_result_2 = np.where((2 < numbers) & (numbers < 6))
print("Where result 2 : ", numbers[where_result_2])

condition_array = np.where(numbers > 5, numbers * 4, numbers * 5)
"""
    explanation
        if numbers > 5:
            numbers * 4
        else :
            numbers * 5
"""
print("Condition array : ", condition_array)

Indices :  [0 2 4]
Where result :  [ 6  7  8  9 10 11 12]
Where result 2 :  [3 4 5]
Condition array :  [ 0  5 10 15 20 25 24 28 32 36 40 44 48]
