# Numpy array operations

In [70]:
import numpy as np

arr_1 = np.arange(20)
print("Basic Slicing : ", arr_1[2:15])
print("With Step : ", arr_1[2:15:2])
print("Negative indexing : ", arr_1[-3])

Basic Slicing :  [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
With Step :  [ 2  4  6  8 10 12 14]
Negative indexing :  17


In [71]:
arr_2_2d = np.array([
    [1,3,5,4],
    [3,54,2,3],
    [4,5,6,8]
])

print("2D Array : \n", arr_2_2d)

print("Specific element : ", arr_2_2d[1, 3])

2D Array : 
 [[ 1  3  5  4]
 [ 3 54  2  3]
 [ 4  5  6  8]]
Specific element :  3


In [72]:
print("Entire row : ", arr_2_2d[1])
print("Entire column : ", arr_2_2d[:, 3])

Entire row :  [ 3 54  2  3]
Entire column :  [4 3 8]


### Sorting

In [73]:
unsorted_1 = np.array([4,8,1,798,2,5,71,5,9,87,1,2,8,7])
print("Unsorted : ", unsorted_1)
print("Sorted : ", np.sort(unsorted_1))

Unsorted :  [  4   8   1 798   2   5  71   5   9  87   1   2   8   7]
Sorted :  [  1   1   2   2   4   5   5   7   8   8   9  71  87 798]


In [74]:
unsorted_2_2d = np.array([
    [11,2],
    [31,4],
    [5,61],
])
print("Unsorted : \n", unsorted_2_2d)
print("\nSorted 2d array by Column: \n", np.sort(unsorted_2_2d, axis=0))
print("\nSorted 2d array by Row: \n", np.sort(unsorted_2_2d, axis=1))

Unsorted : 
 [[11  2]
 [31  4]
 [ 5 61]]

Sorted 2d array by Column: 
 [[ 5  2]
 [11  4]
 [31 61]]

Sorted 2d array by Row: 
 [[ 2 11]
 [ 4 31]
 [ 5 61]]


### Filter

In [75]:
numbers = np.arange(13)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers : ", even_numbers)

Even Numbers :  [ 0  2  4  6  8 10 12]


### Filter with a mask

In [76]:
mask = numbers > 5
print("Mask : ", mask)
print("Number greater than 5 : ", numbers[mask])

Mask :  [False False False False False False  True  True  True  True  True  True
  True]
Number greater than 5 :  [ 6  7  8  9 10 11 12]


### Indexing vs np.where()

In [77]:
indices = [0, 2, 4]
print("Indices : ", numbers[indices])

where_result = np.where(numbers > 5)
print("Where result : ", numbers[where_result])

where_result_2 = np.where((2 < numbers) & (numbers < 6))
print("Where result 2 : ", numbers[where_result_2])

condition_array = np.where(numbers > 5, numbers * 4, numbers * 5)
"""
    explanation
        if numbers > 5:
            numbers * 4
        else :
            numbers * 5
"""
print("Condition array : ", condition_array)

Indices :  [0 2 4]
Where result :  [ 6  7  8  9 10 11 12]
Where result 2 :  [3 4 5]
Condition array :  [ 0  5 10 15 20 25 24 28 32 36 40 44 48]


### Adding and Removing data

In [78]:
arr_1, arr_2 = np.array([1, 2, 3]), np.array([4, 5, 6])
combined = arr_1 +  arr_2
print("Combined : ", combined)
concatenate_array = np.concatenate((arr_1, arr_2))
print("Concatenated : ", concatenate_array)

Combined :  [5 7 9]
Concatenated :  [1 2 3 4 5 6]


### Array Compatibility

In [79]:
arr_1 = np.arange(4)
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7,8,9])
print("Compatibility Shapes : ", arr_1.shape == arr_2.shape == arr_3.shape)

Compatibility Shapes :  False


In [80]:
original = np.array([
    [1,2],
    [4, 5],
])

new_row = np.array([[7, 8]])
new_col = np.array([
    [3],
    [6],
])
with_new_row = np.vstack((original, new_row)) # add new row, vstack always add row
with_new_col = np.hstack((original, new_col)) # add new column
print("Original : ", original)
print("With new row : ", with_new_row)
print("With new col : ", with_new_col)


Original :  [[1 2]
 [4 5]]
With new row :  [[1 2]
 [4 5]
 [7 8]]
With new col :  [[1 2 3]
 [4 5 6]]


### Delete Operation

In [81]:
arr = np.array([
    [1, 2, 3], [4, 5, 6], [7, 8, 9],
])

deleted = np.delete(arr, 6) # this will remove number 7

print("Array : ", arr)
print("Deleted : ", deleted)

Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Deleted :  [1 2 3 4 5 6 8 9]
