<a href="https://colab.research.google.com/github/TajwarSaiyeed/learn-numpy-cc/blob/main/Array_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**1) Converting Python sequences to NumPy arrays**

In [2]:
array1d = np.array([1, 2, 3, 4])
array2d = np.array([[
    1, 2, 3
], [
    4, 5, 6
]])
array3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(array1d)
print(array2d)
print(array3d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Dtype**

In [5]:
np.array([127, 128, 129], dtype=np.int8)
# An 8-bit signed integer represents integers from -128 to 127.
# ---------------------------------------------------------------------------
# OverflowError                             Traceback (most recent call last)
# /tmp/ipython-input-2745257341.py in <cell line: 0>()
# ----> 1 np.array([127, 128, 129], dtype=np.int8)

# OverflowError: Python integer 128 out of bounds for int8


OverflowError: Python integer 128 out of bounds for int8

 # uint32 and int32 can both be represented in as int64.

In [6]:
a = np.array([2,3,4], dtype=np.uint32)
print(a)
b = np.array([5, 6, 7], dtype=np.uint32)
print(b)
c_unsigned32 = a - b
print("unsigned c : ", c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print("signed c : ", c_signed32, c_signed32.dtype)

[2 3 4]
[5 6 7]
unsigned c :  [4294967293 4294967293 4294967293] uint32
signed c :  [-3 -3 -3] int64


In [7]:
# Return a new array of given shape and type, without initializing entries.
# Doc : https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty

a = np.empty(shape=(2, 3), dtype=np.int8, order="F", device='cpu')
print(a)

[[-68   2   0]
 [  5   0   0]]


In [8]:
# numpy.empty_like
# Return a new array with the same shape and type as a given array.
# Doc : https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html#numpy.empty_like

a = ([1,2,3], [4,5,6])
np.empty_like(prototype=a, dtype=np.long, order="F", shape=(2, 3), device='cpu', subok=True)

array([[         131681, 133192569905984, 133193123358080],
       [              0, 133192569906032,    152198908976]])

In [9]:
x = np.arange(10, dtype=np.int32)
x.reshape((2, 5))
print("X array ", x)

# Zero like : https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html#numpy.zeros_like
zeros = np.zeros_like(x, dtype=np.float16, order="F", subok=True, shape=(2,5))
print("Zeros : ", zeros, "\n")
# One Like : https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like
ones =np.ones_like(x, dtype=np.long, order="F", subok=True, shape=(5,2))
print("Ones : ", ones)

X array  [0 1 2 3 4 5 6 7 8 9]
Zeros :  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Ones :  [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [10]:
# Full Like : https://numpy.org/doc/stable/reference/generated/numpy.full_like.html#numpy.full_like
# numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None, *, device=None)

x_full_like = np.full_like(x, np.nan, dtype=np.bool, order="F", subok=True, shape=(2,5))
print("X Full Like : ", x_full_like, "\n")

y = np.arange(6, dtype=np.double)
y_full_like = np.full_like(y, 0.1)
print("Y Full Like : ", y_full_like)
print(type(y_full_like[0]), "\n")

z = np.zeros([2, 2, 3], dtype=int)
np.full_like(z, [4, 5, 255])



X Full Like :  [[ True  True  True  True  True]
 [ True  True  True  True  True]] 

Y Full Like :  [0.1 0.1 0.1 0.1 0.1 0.1]
<class 'numpy.float64'> 



array([[[  4,   5, 255],
        [  4,   5, 255]],

       [[  4,   5, 255],
        [  4,   5, 255]]])

In [11]:
# numpy.identity : https://numpy.org/doc/stable/reference/generated/numpy.identity.html
# Return the identity array.

# numpy.identity(n, dtype=None, *, like=None)
np.identity(5, dtype=np.float128, like=None)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float128)

In [13]:
# numpy.eye : https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
# N = rows, M = columns

eye_array = np.eye(N=4, M=4, k=0, dtype=np.int8, order='C')
print(eye_array)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [27]:
# https://numpy.org/doc/stable/reference/generated/numpy.array.html
# Create an array.
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

a1 = np.array([
    [1, 2],
    [3, 4]
])
print(a1)

a2 = np.array([1, 2, 3.0])
print(a2)

# Minimum dimensions 2:

dimn_array = np.array([[1, 2, 3,], [4, 5, 6]], ndmin=2)
print(dimn_array)


# Complex datatype array
cmp_arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
print(cmp_arr)

# subclass
np.array(np.asmatrix('1 2; 3 4'))
np.array(np.asmatrix('1 2; 3 4'), subok=True)

[[1 2]
 [3 4]]
[1. 2. 3.]
[[1 2 3]
 [4 5 6]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


matrix([[1, 2],
        [3, 4]])