<a href="https://colab.research.google.com/github/TajwarSaiyeed/learn-numpy-cc/blob/main/Array_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

**1) Converting Python sequences to NumPy arrays**

In [23]:
array1d = np.array([1, 2, 3, 4])
array2d = np.array([[
    1, 2, 3
], [
    4, 5, 6
]])
array3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(array1d)
print(array2d)
print(array3d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Dtype**

In [24]:
np.array([127, 128, 129], dtype=np.int8)
# An 8-bit signed integer represents integers from -128 to 127.
# ---------------------------------------------------------------------------
# OverflowError                             Traceback (most recent call last)
# /tmp/ipython-input-2745257341.py in <cell line: 0>()
# ----> 1 np.array([127, 128, 129], dtype=np.int8)

# OverflowError: Python integer 128 out of bounds for int8


OverflowError: Python integer 128 out of bounds for int8

 # uint32 and int32 can both be represented in as int64.

In [ ]:
a = np.array([2,3,4], dtype=np.uint32)
print(a)
b = np.array([5, 6, 7], dtype=np.uint32)
print(b)
c_unsigned32 = a - b
print("unsigned c : ", c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print("signed c : ", c_signed32, c_signed32.dtype)

In [ ]:
# Return a new array of given shape and type, without initializing entries.
# Doc : https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty

a = np.empty(shape=(2, 3), dtype=np.int8, order="F", device='cpu')
print(a)