<a href="https://colab.research.google.com/github/TajwarSaiyeed/learn-numpy-cc/blob/main/Array_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

**1) Converting Python sequences to NumPy arrays**

In [5]:
array1d = np.array([1, 2, 3, 4])
array2d = np.array([[
    1, 2, 3
], [
    4, 5, 6
]])
array3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(array1d)
print(array2d)
print(array3d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Dtype**

In [6]:
np.array([127, 128, 129], dtype=np.int8)
# An 8-bit signed integer represents integers from -128 to 127.
# ---------------------------------------------------------------------------
# OverflowError                             Traceback (most recent call last)
# /tmp/ipython-input-2745257341.py in <cell line: 0>()
# ----> 1 np.array([127, 128, 129], dtype=np.int8)

# OverflowError: Python integer 128 out of bounds for int8


OverflowError: Python integer 128 out of bounds for int8

 # uint32 and int32 can both be represented in as int64.

In [7]:
a = np.array([2,3,4], dtype=np.uint32)
print(a)
b = np.array([5, 6, 7], dtype=np.uint32)
print(b)
c_unsigned32 = a - b
print("unsigned c : ", c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print("signed c : ", c_signed32, c_signed32.dtype)

[2 3 4]
[5 6 7]
unsigned c :  [4294967293 4294967293 4294967293] uint32
signed c :  [-3 -3 -3] int64


In [8]:
# Return a new array of given shape and type, without initializing entries.
# Doc : https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty

a = np.empty(shape=(2, 3), dtype=np.int8, order="F", device='cpu')
print(a)

[[  -4  -39    0]
 [-101   34    0]]


In [35]:
# numpy.empty_like
# Return a new array with the same shape and type as a given array.
# Doc : https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html#numpy.empty_like

a = ([1,2,3], [4,5,6])
np.empty_like(prototype=a, dtype=np.long, order="F", shape=(2, 3), device='cpu', subok=True)

array([[607837963,         0,         0],
       [        0,         0,         0]])

In [49]:
x = np.arange(10, dtype=np.int32)
x.reshape((2, 5))
print("X array ", x)

# Zero like : https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html#numpy.zeros_like
zeros = np.zeros_like(x, dtype=np.float16, order="F", subok=True, shape=(2,5))
print("Zeros : ", zeros, "\n")
# One Like : https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like
ones =np.ones_like(x, dtype=np.long, order="F", subok=True, shape=(5,2))
print("Ones : ", ones)

[0 1 2 3 4 5 6 7 8 9]
Zeros :  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Ones :  [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [67]:
# Full Like : https://numpy.org/doc/stable/reference/generated/numpy.full_like.html#numpy.full_like
# numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None, *, device=None)

x_full_like = np.full_like(x, np.nan, dtype=np.bool, order="F", subok=True, shape=(2,5))
print("X Full Like : ", x_full_like, "\n")

y = np.arange(6, dtype=np.double)
y_full_like = np.full_like(y, 0.1)
print("Y Full Like : ", y_full_like)
print(type(y_full_like[0]), "\n")

z = np.zeros([2, 2, 3], dtype=int)
np.full_like(z, [4, 5, 255])



X Full Like :  [[ True  True  True  True  True]
 [ True  True  True  True  True]] 

Y Full Like :  [0.1 0.1 0.1 0.1 0.1 0.1]
<class 'numpy.float64'> 



array([[[  4,   5, 255],
        [  4,   5, 255]],

       [[  4,   5, 255],
        [  4,   5, 255]]])

In [69]:
# numpy.identity : https://numpy.org/doc/stable/reference/generated/numpy.identity.html
# Return the identity array.

# numpy.identity(n, dtype=None, *, like=None)
np.identity(5, dtype=np.float128, like=None)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float128)